services:
  app:
    volumes:
      - .:/usr/src/app
    container_name: bot
    image: node:22.16.0
    working_dir: /usr/src/app
    command: bash -c 'npm install -g pnpm && pnpm i && pnpm build && pnpm start'
volumes:
  bot:
