services:
  appdb:
    container_name: appdb
    image: mysql:8.4.2
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 1855:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: Yes
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: aqued
      TZ: 'Asia/Tokyo'
    command: mysqld
    depends_on:
      - appcore
  appcore:
    volumes:
      - .:/usr/src/app
    container_name: appcore
    image: node:22.11.0-slim
    working_dir: /usr/src/app
    command: bash -c 'apt-get update && apt-get -y install git && npm install -g pnpm && pnpm i && pnpm build && pnpm start'
volumes:
  mysql-data:
  appcore:
