services:
  appdb:
    container_name: appdb
    image: mysql:8.4.2
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 1855:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: Yes
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: aqued
      TZ: 'Asia/Tokyo'
    command: mysqld

  appcore:
    container_name: appcore
    image: node:22.14.0-slim
    volumes:
      - .:/usr/src/app
      - pnpm-store:/usr/src/app/.pnpm-store
    working_dir: /usr/src/app
    environment:
      - PNPM_HOME=/usr/src/app/.pnpm
      - PATH=/usr/src/app/.pnpm:$PATH
    command: >
      bash -c "apt-get update && apt-get -y install git &&
      npm install -g pnpm &&
      pnpm config set store-dir /usr/src/app/.pnpm-store &&
      pnpm i &&
      pnpm build &&
      pnpm start"
    depends_on:
      - appdb 

volumes:
  mysql-data:
  pnpm-store:
  appcore:
